<?xml version="1.0"?>
<!DOCTYPE OCDBFoldervsRunRange [
<!ELEMENT OCDBFoldervsRunRange (Folder*)>
<!ELEMENT Folder EMPTY>
<!ATTLIST Folder StartRunRange CDATA #REQUIRED>
<!ATTLIST Folder EndRunRange CDATA #REQUIRED>
<!ATTLIST Folder OCDBFolder CDATA #REQUIRED>
]>
<OCDBFoldervsRunRange>
<Folder StartRunRange="0" EndRunRange="10000"  OCDBFolder="local://$ALICE_ROOT/OCDB">
</Folder>
<Folder StartRunRange="15446" EndRunRange="29184"  OCDBFolder="alien://folder=/alice/data/2008/LHC08a/OCDB">
</Folder>
<Folder StartRunRange="29185" EndRunRange="42390"  OCDBFolder="alien://folder=/alice/data/2008/LHC08b/OCDB">
</Folder>
<Folder StartRunRange="42391" EndRunRange="57680"  OCDBFolder="alien://folder=/alice/data/2008/LHC08c/OCDB">
</Folder>
<Folder StartRunRange="57681" EndRunRange="64787"  OCDBFolder="alien://folder=/alice/data/2008/LHC08d/OCDB">
</Folder>
<Folder StartRunRange="64788" EndRunRange="105523"  OCDBFolder="alien://folder=/alice/data/2009/OCDB">
</Folder>
<Folder StartRunRange="105524" EndRunRange="139674"  OCDBFolder="alien://folder=/alice/data/2010/OCDB">
</Folder>
<Folder StartRunRange="139675" EndRunRange="170718"  OCDBFolder="alien://folder=/alice/data/2011/OCDB">
</Folder>
<Folder StartRunRange="170719" EndRunRange="194479"  OCDBFolder="alien://folder=/alice/data/2012/OCDB">
</Folder>
<Folder StartRunRange="194480" EndRunRange="199999"  OCDBFolder="alien://folder=/alice/data/2013/OCDB">
</Folder>
<Folder StartRunRange="200000" EndRunRange="208504"  OCDBFolder="alien://folder=/alice/data/2014/OCDB">
</Folder>
<Folder StartRunRange="208505" EndRunRange="247170"  OCDBFolder="alien://folder=/alice/data/2015/OCDB">
</Folder>
<Folder StartRunRange="247171" EndRunRange="999999999"  OCDBFolder="alien://folder=/alice/data/2016/OCDB">
</Folder>
</OCDBFoldervsRunRange>
